baseURL = "https://scottvandenwarsen.com/"
languageCode = 'en-us'
title = "Scott Vanden Warsen"
theme = "beautifulhugo"
enableRobotsTXT = true
canonifyURLs = true


[params]
  homeBlurb = "Welcome to an inside look at what Iâ€™m thinking about and want to share with others."

